name: Maven Build and Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  permissions:
  id-token: write # Required to fetch the OIDC token for AWS authentication
  contents: read  # Required for 'actions/checkout' to read your repository code


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Job-level condition: only run if on 'main' branch

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # IMPORTANT: Replace 'YOUR_IAM_ROLE_ARN_GOES_HERE' with the actual ARN of your IAM role from AWS!
          role-to-assume: arn:aws:iam::782860593533:role/githubsasi
          # This must be the AWS region where your SES sender identity is verified.
          aws-region: eu-north-1 # Example: us-east-1

      - name: Build with Maven
        run: mvn clean package

      - name: Publish to GitHub Packages
        run: mvn deploy -s settings.xml
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Verify JAR
        if: success() # Step-level condition: only run if previous steps were successful
        run: ls -l target/
      - name: Send Email Notification (on success)
        # This step runs ONLY if all previous steps in this job have succeeded.
        if: success()
        run: |
          # The 'aws ses send-email' command directly calls the AWS SES API.
          # The 'from' address MUST be an identity you verified in AWS SES.
          # The 'to' address will receive the email. If your SES account is in sandbox, 'to' must also be verified.
          aws ses send-email \
            --from 'hannap607@gmail.com' \
            --destination 'ToAddresses="hannapaikkatt1234@gmail.com"' \
            --message 'Subject={Data="✅ Build Success - ${{ github.repository }}"},Body={Text={Data="Build for ${{ github.repository }} on branch `${{ github.ref_name}}` was successful!\n\nCommit: `${{ github.sha}}`\nWorkflow Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}}' \
            --region eu-north-1 # Ensure this matches your aws-region above

      - name: Send Email Notification (on failure)
        # This step runs ONLY if any previous step in this job has failed.
        if: failure()
        run: |
          aws ses send-email \
            --from 'hannap607@gmail.com' \
            --destination 'ToAddresses="hannapaikkatt1234@gmail.com"' \
            --message 'Subject={Data="❌ Build FAILED - ${{ github.repository }}"},Body={Text={Data="*ALERT:* Build for ${{ github.repository }} on branch `${{ github.ref_name}}` *FAILED!*\n\nCommit: `${{ github.sha}}`\n*Please review logs:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}}' \
            --region eu-north-1
